name: macOS x86_64 to macOS M1 Apple clang
on: [push, pull_request]

jobs:
  splitByBuildTypesTrue:
    runs-on: ${{ matrix.config.image }}
    strategy:
      fail-fast: false
      matrix:
        config:
          - { image: macos-11, version: "12.5.1", versionForConan: "12.0", buildType: "Debug"   }
          - { image: macos-11, version: "12.5.1", versionForConan: "12.0", buildType: "Release" }
          - { image: macos-11, version: "13.0",   versionForConan: "13.0", buildType: "Debug"   }
          - { image: macos-11, version: "13.0",   versionForConan: "13.0", buildType: "Release" }
    name: APPLE_CLANG ${{ matrix.config.version }} ${{ matrix.config.buildType }}
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: ">=3.9.2"
      - uses: maxim-lobanov/setup-xcode@v1.4.0
        with:
          xcode-version: ${{ matrix.config.version }}
      - name: Install Conan
        run: |
          pip install conan_package_tools
          conan user
      - name: Create build & host profile for conan
        run: |
          conan profile new build
          conan profile update settings.os=Macos build
          conan profile update settings.arch=x86_64 build
          conan profile update settings.compiler=apple-clang build
          conan profile update settings.compiler.version=${{ matrix.config.versionForConan }} build
          conan profile update settings.compiler.libcxx=libc++ build
          conan profile update settings.build_type=Release build
          conan profile new host
          conan profile update settings.os=Macos host
          conan profile update settings.arch=armv8 host
          conan profile update settings.compiler=apple-clang host
          conan profile update settings.compiler.version=${{ matrix.config.versionForConan }} host
          conan profile update settings.compiler.libcxx=libc++ host
          conan profile update settings.build_type=${{ matrix.config.buildType }} host
      - name: Run
        env:
          CONAN_ARCHS: armv8
          CONAN_APPLE_CLANG_VERSIONS: ${{ matrix.config.versionForConan }}
          CONAN_BUILD_TYPES: ${{ matrix.config.buildType }}
          CONAN_BASE_PROFILE_BUILD: build
          CONAN_BASE_PROFILE: host
        run: |
          python build.py
